### ISSUE TITLE
Disable Falcosidekick

### ISSUE THREAD

**Issue by marwinski** [gardener/gardener-extension-shoot-falco-service#85]
**What would you like to be added**:

Configure the Falco deployment to run without Falcosidekick. This means that the events are only stored in the Falco pod stdout log.

**Why is this needed**:

As a user I want to scrape Falco event logs myself and not rely on Falcosidekick to send events to an event store. This can be done today already, however events are still sent to a central event store.

**Comment by lsroe** [comment]
We could consider looking at fluent-bit/fluent-d. They also allow forwarding to a wide range of [targets](https://www.fluentd.org/dataoutputs).

**Comment by marwinski** [comment]
superseded by https://github.com/gardener/gardener-extension-shoot-falco-service/issues/107. Our goal is to make this as flexible as possible and use Falcosidekick wherever possible and when needed.
